site_name: 备忘录
site_description: 怕自己忘的备忘录qvq
site_author: Liueic Aicnal

copyright: Copyright 2024 Liueic Aicnal

# 代码仓库信息
repo_name: Aicnal/help-docs
repo_url: https://github.com/Aicnal/help-docs

nav:
  - 主页: index.md
  - 在上网前应该知道的:
    - 提问的智慧: 在上网前应该知道的/how-to-ask.md
  - 基本技能:
    - Git: 基本技能/git.md
    - Vim: 基本技能/vim.md
    - 配置 SSH 密钥与签名: 基本技能/配置SSH密钥与签名.md
  - MJJ的基本素养:
    - OpenSSH: MJJ的基本素养/Openssh.md
    - Fail2ban: MJJ的基本素养/Fail2ban.md
  - Discourse 运维:
    - Discourse 安装: Discourse/Install.md
    - Discourse 插件: Discourse/plugin.md
    - Discourse admin配置: Discourse/admin.md

theme:
  name: material
  palette:
    scheme: light  # dark 或者 light
    primary: indigo  # 主色调
    accent: blue     # 辅助色
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search:
      separator: '[\s\u200b\-]'
  - minify: 
      minify_html: true

markdown_extensions: # markdown extensions
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css
  - https://cdn.staticfile.org/lxgw-wenkai-screen-webfont/1.7.0/lxgwwenkaiscreen.css