site_name: 备忘录
site_description: 一个简单的备忘录
nav:
  - 主页: index.md
  - 关于: about.md

theme:
  name: material
  palette:
    scheme: default  # dark 或者 light
    primary: indigo  # 主色调
    accent: pink     # 辅助色
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - minify: 
      minify_html: true